#!/bin/bash

#################################
#
#    usage error
#    
#################################
if [ $# -eq 0 ] 
then
    echo """
    Usage: xxx PATTERN 
    """
    exit 1
fi

>output_file # clear old data

#################################
#
#    billie's xxx
#    
#################################

data=`find . -type d -name .git -prune -o \( \! -name ddd \) -exec grep -in "$1" {} + `
echo "$data">output_file

if [ -z "$data" ] ## output_file is empty, so no match, quit
then
    echo  no match
    rm output_file 
    exit 
fi

#################################
#
#    process output_file
#    
#################################

declare -a thefilename
declare -a linenumber

count=0
while read line; do 
    echo -ne "\033[1m NO.$(( ++count )):\033[0m"
    thefilename[$count]=`echo $line|awk -F":" '{print $1}'`
    linenumber[$count]=`echo $line|awk -F":" '{print $2}'`
    linecontent=`echo $line|awk -F":" '{print $3 ":" $4}'` 
    # FIXME: the above works when the line has "http://xxx" as content, still buggy
    
    echo ${thefilename[$count]}
    printf "\t $linecontent \n" # echo will expand special characters like * 
done < output_file
rm output_file

#################################
#
#    choose
#    
#################################

echo 
echo 
echo -n " Now which one do you want to open? [1,2,3...]  "
read nu

vim +${linenumber[$nu]} ${thefilename[$nu]}
